version: "3.8"
services:

  db:
    image: postgres:13-alpine
    container_name: postgres13
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - "./docker/db/data:/var/lib/postgresql/data"
      - "./docker/db/backup:/var/tmp"
