version: '3.9'

volumes:
  data: {}
  backup: {}

services:

  postgres:
    image: postgres:12
    container_name: kaa-pg
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
      - backup:/media/postgresql/backup
    environment:
      POSTGRES_USER: "test-admin-user"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test_db"
    restart: always
