resource "local_file" "inventory" {
  content = <<-EOT
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

    # Node List

    [srv01nginx]
    nginx ansible_host=${yandex_compute_instance.srv01nginx.network_interface.0.nat_ip_address}

    [srv02db01]
    db01 ansible_host=${yandex_compute_instance.srv02db01.network_interface.0.ip_address}

    [srv03db02]
    db02 ansible_host=${yandex_compute_instance.srv03db02.network_interface.0.ip_address}

    [srv04app]
    app ansible_host=${yandex_compute_instance.srv04app.network_interface.0.ip_address}

    [srv05gitlab]
    gitlab ansible_host=${yandex_compute_instance.srv05gitlab.network_interface.0.ip_address}

    [srv06runner]
    runner ansible_host=${yandex_compute_instance.srv06runner.network_interface.0.ip_address}

    [srv07monitoring]
    monitoring ansible_host=${yandex_compute_instance.srv07monitoring.network_interface.0.ip_address}

    # Servers group

    [myallhosts:children]
    srv01nginx
    srv02db01
    srv03db02
    srv04app
    srv05gitlab
    srv06runner
    srv07monitoring

    [mydb:children]
    srv02db01
    srv03db02

    #
    # Vars for group and hosts
    #

    [srv01nginx:vars]
    my_domain = "${var.my_domain}"
    le_staging = "${var.my_le_staging}"

    [mydb:vars]
    my_replicator_psw = "${var.my_replicator_psw}"

    [srv02db01:vars]
    ansible_ssh_common_args='-o ControlMaster=auto -o ControlPersist=10m -o ProxyCommand="ssh -W %h:%p -q ubuntu@${yandex_compute_instance.srv01nginx.network_interface.0.nat_ip_address}"'
    mysql_replication_role = "master"

    [srv03db02:vars]
    ansible_ssh_common_args='-o ControlMaster=auto -o ControlPersist=10m -o ProxyCommand="ssh -W %h:%p -q ubuntu@${yandex_compute_instance.srv01nginx.network_interface.0.nat_ip_address}"'
    mysql_replication_role = "slave"

    [srv04app:vars]
    ansible_ssh_common_args='-o ControlMaster=auto -o ControlPersist=10m -o ProxyCommand="ssh -W %h:%p -q ubuntu@${yandex_compute_instance.srv01nginx.network_interface.0.nat_ip_address}"'
    my_domain = "${var.my_domain}"

    [srv05gitlab:vars]
    ansible_ssh_common_args='-o ControlMaster=auto -o ControlPersist=10m -o ProxyCommand="ssh -W %h:%p -q ubuntu@${yandex_compute_instance.srv01nginx.network_interface.0.nat_ip_address}"'
    my_gitlab_psw = "${var.my_gitlab_psw}"
    my_gitlab_runner = "${var.my_gitlab_runner}"
    my_domain = "${var.my_domain}"

    [srv06runner:vars]
    ansible_ssh_common_args='-o ControlMaster=auto -o ControlPersist=10m -o ProxyCommand="ssh -W %h:%p -q ubuntu@${yandex_compute_instance.srv01nginx.network_interface.0.nat_ip_address}"'
    my_gitlab_runner = "${var.my_gitlab_runner}"
    my_domain = "${var.my_domain}"

    [srv07monitoring:vars]
    ansible_ssh_common_args='-o ControlMaster=auto -o ControlPersist=10m -o ProxyCommand="ssh -W %h:%p -q ubuntu@${yandex_compute_instance.srv01nginx.network_interface.0.nat_ip_address}"'
    my_grafana_psw = ${var.my_grafana_psw}

    [myallhosts:vars]
    my_domain = "${var.my_domain}"
    ip_srv01nginx = ${yandex_compute_instance.srv01nginx.network_interface.0.ip_address}
    ip_srv02db01 = ${yandex_compute_instance.srv02db01.network_interface.0.ip_address}
    ip_srv03db02 = ${yandex_compute_instance.srv03db02.network_interface.0.ip_address}
    ip_srv04app = ${yandex_compute_instance.srv04app.network_interface.0.ip_address}
    ip_srv05gitlab = ${yandex_compute_instance.srv05gitlab.network_interface.0.ip_address}
    ip_srv06runner = ${yandex_compute_instance.srv06runner.network_interface.0.ip_address}
    ip_srv07monitoring = ${yandex_compute_instance.srv07monitoring.network_interface.0.ip_address}

    EOT
  filename = "./ansible/inventory.yml"
  file_permission = "0644"

  depends_on = [
    yandex_compute_instance.srv01nginx,
    yandex_compute_instance.srv02db01,
    yandex_compute_instance.srv03db02,
    yandex_compute_instance.srv04app,
    yandex_compute_instance.srv05gitlab,
    yandex_compute_instance.srv06runner,
    yandex_compute_instance.srv07monitoring
  ]
}
